spring:
  datasource:
    url: jdbc:postgresql://localhost:5333/subscription-manager
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
token:
  spring:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855



